artifacts_root: "artifacts"

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/aditya0589/datasets/raw/refs/heads/main/wine-quality.zip
  local_data_file: artifacts/data/winequality-red.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/wine-quality.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/wine-quality.csv


