artifacts_root: "artifacts"

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/aditya0589/datasets/raw/refs/heads/main/wine-quality.zip
  local_data_file: artifacts/data/winequality-red.csv
  unzip_dir: artifacts/data_ingestion

